using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Planet : MonoBehaviour
{

    [Range(2, 256)]
    public int resolution = 32;
    public bool autoUpdate = true;
    public enum FaceRenderMask { All, Top, Bottom, Left, Right, Front, Back }; //option to render 1 face at a time to gain time
    public FaceRenderMask faceRenderMask;

    public ShapeSettings shapeSettings; // link shape editor
    public ColourSettings colourSettings; // link color editor

    [HideInInspector]
    public bool shapeSettingsFoldout;
    [HideInInspector]
    public bool colourSettingsFoldout;

    ShapeGenerator shapeGenerator = new ShapeGenerator(); // use shapeGenerator object to update shape
    ColourGenerator colourGenerator = new ColourGenerator(); // use this object to update colors

    [SerializeField, HideInInspector]
    MeshFilter[] meshFilters; // a mesh filter holds a reference to a mesh
    TerrainFace[] terrainFaces;

    // Initialize mesh filters for each terrain face
    void Initialize()
    {
        shapeGenerator.UpdateSettings(shapeSettings); // Create shape generator from current shape settings
        colourGenerator.UpdateSettings(colourSettings); // Create colour generator from curret colour settings

        if (meshFilters == null || meshFilters.Length == 0) // check if the mesh filter needs to be initialized
        {
            meshFilters = new MeshFilter[6];
        }
        terrainFaces = new TerrainFace[6];

        Vector3[] directions = { Vector3.up, Vector3.down, Vector3.left, Vector3.right, Vector3.forward, Vector3.back };

        for (int i = 0; i < 6; i++)
        {
            if (meshFilters[i] == null)
            {
                GameObject meshObj = new GameObject("mesh");
                meshObj.transform.parent = transform;

                meshObj.AddComponent<MeshRenderer>();
                meshFilters[i] = meshObj.AddComponent<MeshFilter>();
                meshFilters[i].sharedMesh = new Mesh { name = $"PlanetFace_{i}" };
            }

            // ── FIX : le composant MeshFilter peut survivre (référence sérialisée
            // valide) alors que son Mesh, lui, ne l'est pas : un "new Mesh()" créé
            // en mémoire n'est jamais persisté avec le prefab/la scène. Après un
            // rechargement (fermeture Unity, entrée/sortie du mode édition de
            // prefab...), sharedMesh redevient None et ConstructMesh() plante avec
            // une NullReferenceException. On le recrée si besoin, indépendamment
            // de l'état du composant lui-même.
            if (meshFilters[i].sharedMesh == null)
            {
                meshFilters[i].sharedMesh = new Mesh { name = $"PlanetFace_{i}" };
            }

            meshFilters[i].GetComponent<MeshRenderer>().sharedMaterial = colourSettings.planetMaterial;

            terrainFaces[i] = new TerrainFace(shapeGenerator, meshFilters[i].sharedMesh, resolution, directions[i]);
            bool renderFace = faceRenderMask == FaceRenderMask.All || (int)faceRenderMask - 1 == i; // true if facerendermask is set to all or if facerendermask is set to current face
            meshFilters[i].gameObject.SetActive(renderFace); //set active is renderFace is true
        }
    }

    // Generate a planet including shape and color settings
    public void GeneratePlanet()
    {
        Initialize();
        GenerateMesh();
        GenerateColours();
    }

    /// <summary>
    /// Variant of GeneratePlanet() to be called by game code
    /// (e.g. SolarSystemGenerator) rather than by the publisher.
    ///
    /// Problem avoided: Planet.Initialize() assigns directly
    /// colourSettings.planetMaterial (a SHARED ASSET) with each MeshRenderer.
    /// If several planets use the same ColourSettings, they write
    /// all in the SAME Material (_elevationMinMax, _texture): the last
    /// generated planet visually crushes all the others.
    ///
    /// This method clones the ColourSettings and its Material for this
    /// instance only, without ever touching the original shared asset.
    /// The instantiated ScriptableObject (and their Material) are cleaned up
    /// automatically by Unity when the object is destroyed.
    /// </summary>
    public void GeneratePlanetRuntime(ShapeSettings shape, ColourSettings colour)
    {
        if (shape == null || colour == null)
        {
            Debug.LogWarning("[Planet] GeneratePlanetRuntime appelé avec des settings null.", this);
            return;
        }

        shapeSettings = shape; // lecture seule, sans danger à partager entre planètes
        colourSettings = Instantiate(colour); // private copy of color settings
        colourSettings.planetMaterial = new Material(colour.planetMaterial); // Unique material for this planet

        GeneratePlanet();
    }

    /// <summary>Radius (local space) of the sphere generated by this ShapeSettings.</summary>
    public float GetBaseRadius()
    {
        return shapeSettings != null ? shapeSettings.planetRadius : 0.5f;
    }

    /// <summary>
    /// Show the currently generated meshes (used by PlanetEditor for
    /// save them as a subasset of the prefab and avoid not
    /// return to "None" after a reload). It does nothing at runtime.
    /// </summary>
    public IEnumerable<Mesh> GetGeneratedMeshes()
    {
        if (meshFilters == null) yield break;

        foreach (MeshFilter mf in meshFilters)
        {
            if (mf != null && mf.sharedMesh != null)
                yield return mf.sharedMesh;
        }
    }

    // Update shape (mesh) if shape settings have changed
    public void OnShapeSettingsUpdated()
    {
        if (autoUpdate)
        {
            Initialize();
            GenerateMesh();
        }
    }

    // Update colors if color settings have changed
    public void OnColourSettingsUpdated()
    {
        if (autoUpdate)
        {
            Initialize();
            GenerateColours();
        }
    }

    // Generate mesh for each terrain face
    void GenerateMesh()
    {
        for (int i = 0; i < 6; i++)
        {
            if (meshFilters[i].gameObject.activeSelf)
            {
                terrainFaces[i].ConstructMesh();
            }
        }
        colourGenerator.UpdateElevation(shapeGenerator.elevationMinMax);
    }

    // Generate color from colourSettings editor
    void GenerateColours()
    {
        colourGenerator.UpdateColours();
        for (int i = 0; i < 6; i++)
        {
            if (meshFilters[i].gameObject.activeSelf)
            {
                terrainFaces[i].UpdateUVS(colourGenerator);
            }
        }
    }
}